### ISSUE TITLE
waiting for available sockets(Chrome)

### ISSUE THREAD

**Issue by 45sound** [23/resumable.js#143]
After trying 4 other uploaders, resumablejs beats them all hands down! :)

I upload a 100 MB video with resumable and with simultaneousUploads set to 10. 
I open a new tab and go to the same website. While the files are still uploading in the first tab, the new tab does not load. 
In the status bar in Chrome, it says: "waiting for available sockets". 

Is this due to simultaneousUploads been set so high? Any way to work around this?

Best,
Vinny

**Comment by Rameshvolkar** [comment]
How to fix error, “waiting for available sockets” in Google Chrome

Waiting for available sockets error on chrome basically happens due to overload images and data saved on chrome.Cookies and images saved on chrome once gets in huge it creates this error.Solution for [http://www.fixotip.com/how-to-fix-error-waiting-for-available-sockets-in-google-chrome/](url) is very easy just open previous this url and follow the steps.

Whenever we do open any site it saves some cookies and images as temporary on browser.For the time being it reaches into overload and creates available socket error.and it will show in the bottom left corner of the screen.
