### ISSUE TITLE
Using JSON responses rather then HTTP response status for testChunk

### ISSUE THREAD

**Issue by relector-tuxnix** [23/resumable.js#160]
Enabling 'testChunk' means if a chunk is not found a 404 (or non 200 HTTP status) is returned. Although this is perfectly valid API design its quite annoying to see lots of 404's in my logs etc. Can I propose the the following change:

If a chunk is found return the following JSON:

```
{"success":true,"message":"Chunk found."}
```

If a chunk is not found return the following JSON:

```
{"success":false,"message":"Chunk not found."}
```

The following code changes can be made in resumable.js:

```
                var testHandler = function(e) {

                        $.tested = true;

                        var status = $.status();

                        if(status=='success') {

                                var response = JSON.parse($.xhr.responseText);

                                if(response.success == false) {
                                        $.send();
                                } else {
                                        $.callback(status, $.message());
                                        $.resumableObj.uploadNextChunk();
                                }
                        } else {
                                console.log("HTTP Error.");
                        }
                };
```

**Comment by meden** [comment]
While this bug has already been closed, here are my 2cents: to be semantically correct, any 2xx status code should be interpreted as a successful upload. The difference between success codes are only to notify the client about particular conditions, so that it could behave accordingly (i.e. not trying to build a DOM if it receives 204 No Content).
Maybe a good response for a missing chunk test could be 100 Continue. But it has the limitation of being a HTTP/1.1-only response code (it is not defined in HTTP/1.0).
For further informations, read https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.

Thanks for you work!
