### ISSUE TITLE
Files are being loaded sequentially and not in porallel

### ISSUE THREAD

**Issue by ravindermahajan890** [23/resumable.js#189]
Hi,

As observed, it does allow multiple files to be uploaded however it does not allow files to be uploaded parallely.

i want my files to be uploaded in parallel.

**Comment by icruces** [comment]
@steffentchr Sorry to comment on this old ticket but I just hit this issue. I see your point but I disagree that "there's no performance gain" as it strongly depends on the server implementation/file system.
In my case, my backend streams the data received from the browser to an external distributed system. This distributed system then creates the file in one of its nodes.

Setting `simultaneousUploads` options higher than 1 is useless in this case because the distributed system API doesn't allow either, creating a partial file for each chunk and then merging them or having multiple threads writing different chunks to the same file.

However, it is possible to write different files at the same time, actually it is very efficient, as different files are hosted by different nodes. So having the option to send chunks from different files would drastically improve the performance in this case.

I am actually using ng-flow (the angular wrapper) but saw adequate commenting here.

Cheers.

**Comment by steffentchr** [comment]
That's a good point -- hadn't thought of it since our own file storage is not tied up this way. 
- Two theoretical questions: Since you backbone connection (i/o on the file) will be much faster that the upload, how much is actually gained form writing multiple files at the same time?
- Is there no good way of buffering chunks and then flushing on the web server? This seems like it would be needed in either case for resiliency, and a local 1 MB buffer for each chunk wouldn't be much of a drain on local memory -- or am I missing something?
