### ISSUE TITLE
Include button in events

### ISSUE THREAD

**Issue by spficklin** [23/resumable.js#246]
I am experimenting using resumable.js on a form that has multiple buttons. Each button represents a different type of file but all files have the same extension so it's not possible to distinguish between files by their extensions.  Is it possible to get the button that was clicked in the 'fileAdded' event of the resumable object?  This way I could look at the button id and identify the type of file.  If not could that functionality be added?  Otherwise it seems I must create a different resumable object for every button.

Thanks

**Comment by steffentchr** [comment]
Hi Stephen, 

There's no out-of-the-box way to do this unfortunately -- that is: there isn't a way to have a single `Resumable` object with that is managing multiple different buttons or drop zones with different settings. If you have a reasonable number of buttons/zones, I would simply create a Resumable object for each and be done with it. 

Otherwise, you should handle buttons/zones outside of the Resumable library (you can copy out the code as needed) and then call `r.addFile()` for each file you need uploaded.

Steffen

**Comment by spficklin** [comment]
Even if the button name were passed in as part of the fileAdded event... that would help tremendously. Is that a feature request that would be considered?

**Comment by steffentchr** [comment]
I don't think it would be added as a part of the standard library -- since there are two ways to add files, browse buttons and file drop zones; and since the latter don't have a name to pass on ;)

Having said that you can find the button in question within `appendFilesFromFileList(...)` using the `event` argument:

        var buttonName = '';
        try {
          buttonName = event.target.parentNode.getAttribute('name')
        } catch(e){};

Steffen

**Comment by spficklin** [comment]
Yes, you're right, no source element on a drag-and-drop.   Thanks for the sample code.  So, just to clarify, is the suggestion that I override the Resumable object's appendFilesFromFileList() function so that I can then get the button name from the event?

**Comment by steffentchr** [comment]
Yup -- at least since you'd need to do custom overrides to use the button name in either case ;)

**Comment by spficklin** [comment]
Okay, I'll give that a try.  Thanks much for your help :-)
