### ISSUE TITLE
Limit uploads to certain file types

### ISSUE THREAD

**Issue by JohnReedLOL** [23/resumable.js#277]
How do I limit uploads to only mp4 or only mp3?

Nevermind, it's fileType: ['mp3', 'mp4']

**Comment by donut** [comment]
Along these lines, it would be nice to be able to set the [`accept` parameter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept) through the configuration. Currently, I'm setting it after I run `.assignBrowse()`.

**Comment by steffentchr** [comment]
@donut Yeah, the problem is that the browse option and the drop option uses two different method -- and only the former has an `<input>` that would be able to use the `accept` parameter. Also accept with filename is only formally support by Firefox according to the Mozilla dev center. So using this option would create a pretty skewed user experience where stuff would act differently only when users browse rather than drop; and only in Firefox.

Steffen

**Comment by donut** [comment]
@steffentchr Looks like MDN is out of date, `accept` is [supported in IE 10 and 11, Firefox, Chrome, Safari, and Opera](http://caniuse.com/#search=accept). Anyways, I don't see the feature difference being noticed by users. When it's supported and the user clicks, the browse dialog will filter out non-relevant files. If it's not supported, all files will be selectable. In that situation, it will fall back to the extension filter done in JavaScript. Seems like it degrades pretty gracefully and I doubt it would add any confusion.

I mostly just wanted to bring awareness to the feature. It's trivial to add it retrospectively after the `<input>` has been inserted.

**Comment by donut** [comment]
@steffentchr So, I scrapped using the `accept` attribute. Safari on OS X didn't see a .mp4 file as a video file. Never mind about all of this. You're right, it's too early.

**Comment by steffentchr** [comment]
Yeah, when I last tested `video/*` was unusable -- I didn't know about the extension thing though.
