### ISSUE TITLE
change options like chunksize on the fly

### ISSUE THREAD

**Issue by adamjimenez** [23/resumable.js#303]
I couldn't find a way to change the chunkSize after creating the resumable object.

Doing this caused problems:
```
r.opts.chunkSize = 20*1024*1024;
```

**Comment by steffentchr** [comment]
Yeah, the constant chunk size is an assumption in how Resumable works: A key part of the method is that there's no assumed order of the uploads. In fact you can upload many chunks at the same time, and some implementations even have the lib upload the last chunk as quickly as possible for meta data inspection. 

Say you have a chunk size of a 1 MB, then it's clear that chunk number five will be start at 4 MB and end at 5 MB -- which means that this chunk can be triggered even before chunk number 4 (for example). 

If the chunk size was variable, none of this would be possible -- because chunks 1 through 4 would need to have clearly specified chunk sizes ready before chunk 5 can fire.
