### ISSUE TITLE
files array doesn't contain the file selected

### ISSUE THREAD

**Issue by juneight** [23/resumable.js#307]
We are using the client like below in an HTML app.

```
r.assignBrowse($('.resumable-browse-file')[0]);

r.on('filesAdded', function (files) {
            // process files
        });
```

When I select a file using the **resumable-browse-file** button, the selected file is provided in the **files** array to the **filesAdded** event handler and the upload completes as expected.

However when I select the same file again, the **filesAdded** event handler is called with the **files** array empty. Any ideas why this could be happening?

I noticed that the r.files array contain the files that are uploaded. At r.on('complete'), if I clear the r.files array, then the issue goes away. Should we be cleaning the files array like that to allow the user to select the same file again?

We are using the node.js resumablejs module v 1.0.2.

**Comment by steffentchr** [comment]
Yeah, it happens because the lib checks if the file is already loaded/queued/uploading. If that's the case, then it isn't added again -- and the `files` array may be empty even if a file has been selected.

To avoid the behaviour where `filesAdded` [this line](https://github.com/23/resumable.js/blob/master/resumable.js#L428) could be update to check if `files.length>0`. However, I kinda like the behaviour where `filesAdded` is fired to indicate user actions -- and an empty array argument would indicate that no new files where added as a part of the interaction.

**Comment by juneight** [comment]
Got it. Thank you @steffentchr .

**Comment by steffentchr** [comment]
No problem at all.
