### ISSUE TITLE
File upload failed, rename failure

### ISSUE THREAD

**Issue by oleilei** [23/resumable.js#315]
dear,
Java experiment found that the file on the cross, to pause, and then continue, file upload is completed, rename failure, is always *.temp.

thanks.

**Comment by steffentchr** [comment]
This sounds like a Java issue, not something related to Resumable?

**Comment by akd31** [comment]
@oleilei 
The problem is the block below. Since there is no try catch when you stop and continue to upload the last raf isn't closed.Therefore, you can't rename the file since there is an open raf already. You can figure this out by simply put try catch block and close raf when you catch exception too.

`RandomAccessFile raf = new RandomAccessFile(info.resumableFilePath, "rw");

        //Seek to position
        raf.seek((resumableChunkNumber - 1) * (long)info.resumableChunkSize);

        //Save to file
        InputStream is = request.getInputStream();
        long readed = 0;
        long content_length = request.getContentLength();
        byte[] bytes = new byte[1024 * 100];
        while(readed < content_length) {
            int r = is.read(bytes);
            if (r < 0)  {
                break;
            }
            raf.write(bytes, 0, r);
            readed += r;
        }
        raf.close();`
