### ISSUE TITLE
Deleting an already uploaded file

### ISSUE THREAD

**Issue by mbuehrig** [23/resumable.js#338]
I'm using resumable.js for a project and so far I'm quite amazed by how easy it is. But I have a question, according to the UI concept for the project the user has to be able to delete files again which he already uploaded, so they are saved on the server already.

Is there a possibility by which I can send this server request by resumable.js or have I to make an own ajax request and tell the backend developer what to do?

**Comment by steffentchr** [comment]
@mbuehrig Unfortunately its slightly out of the scope of what Resumable.js does -- since it's a server-side thing with the permissions to match. So you'll need to have some kind of API/ajax method to delete the file, maybe using the same token that you're uploading with if that works within your security model.
