### ISSUE TITLE
Asp.Net WebApi example has a performance issue

### ISSUE THREAD

**Issue by danielnutu** [23/resumable.js#352]
Hi,

I'm trying to write an Asp.Net WebApi controller following your example, but I noticed a performance issue in the code that will make the upload take a long time to finish.

The problem is in this portion of code:

```
[NonAction]
private bool AllChunksAreHere(ResumableConfiguration configuration)
{
	for (int chunkNumber = 1; chunkNumber <= configuration.Chunks; chunkNumber++)
		if (!ChunkIsHere(chunkNumber, configuration.Identifier)) return false;
	return true;
}
```

For a large file (let's say 4096 MB) you'll have 4000+ chunks and for each chunk uploaded there will be a check that all chunks are uploaded ... so that's a 4000 chunks * 4000 checks. It's no problem for smaller files, but a huge performance issue for large files.

I've changed the body of the function a little and now it looks like:
```
   if (configuration.ChunkNumber < configuration.TotalChunks)
      return false;
   return true;
```

where ChunkNumber is `resumableChunkNumber` and TotalChunks is `resumableTotalChunks`, both passed to the upload method of the controller.

Regards,
Daniel Nutu

**Comment by cpnielsen** [comment]
Hi Daniel

While it's true that it's "inefficient" to check all chunks every time, we cannot guarantee the order of chunks in resumable.js - it's quite likely that the "end chunk" is not the last to get uploaded. A better solution is probably to have a server-side cache/counter adds each chunk as it is completed.

Say a file with 4 chunks (1, 2, 3, 4) is sent. Because of glitchy internet (or perhaps a switch from 3G to WiFi), chunks are sent 1, 2, 3, 4 but are received 2, 1, 4, 3. Suddenly chunk 3 is the "final" chunk, but the server will assume that all chunks have been sent when chunk 4 is received and an incomplete file will be assembled.

Creating an efficient server-side check is beyond the scope of this library, but that should be the focus instead of assuming the chunk order.

**Comment by danielnutu** [comment]
Thank you for the clarification!
