### ISSUE TITLE
complete is fired in error case

### ISSUE THREAD

**Issue by hyperknot** [23/resumable.js#358]
I'm uploading a single file with maxFiles = 1.

When the server returns error 415 for wrong file type, the following events are fired:
1. fileError - OK
2. error - OK
3. complete - wrong

I believe complete should not be fired, as the upload has not been completed.

**Comment by rmhubley** [comment]
I have a similar issue with file size limitations.  When a GET is issued to check on a chunk the client should be able to discern between "Chunk not found" and a cancelable error state i.e "Upload file size too large".

**Comment by steffentchr** [comment]
Any reason for not just setting that limitation as an option client side?



Steffen Fagerström Christensen
CTO & Co-founder, TwentyThree ™





+45 2532 7058 [tel:004525327058]
steffen@twentythree.net [steffen@twentythree.net]

TwentyThree™. The Video Marketing Platform.
twentythree.net [http://twentythree.net/]


On Mon, Feb 6, 2017 at 13:06, rmhubley <notifications@github.com> wrote:
I have a similar issue with file size limitations. When a GET is issued to check on a chunk the client should be able to discern between "Chunk not found" and a cancelable error state i.e "Upload file size too large".

**Comment by rmhubley** [comment]
Sure.  Because that would be pretty easy to manipulate to bypass what should be a server concern.

**Comment by steffentchr** [comment]
Sure, you should absolutely check chunks during upload - and return forbidden and errors accordingly. But that had nothing to do with the chunk checks.



Steffen Fagerström Christensen
CTO & Co-founder, TwentyThree ™





+45 2532 7058 [tel:004525327058]
steffen@twentythree.net [steffen@twentythree.net]

TwentyThree™. The Video Marketing Platform.
twentythree.net [http://twentythree.net/]


On Mon, Feb 6, 2017 at 14:36, rmhubley <notifications@github.com> wrote:
Sure. Because that would be pretty easy to manipulate to bypass what should be a server concern.

**Comment by rmhubley** [comment]
That's a good point.  I guess what confused me is sample server implementation ( node + express ).  It appeared that the GET implementation validates the size of the chunk.  Probably should not be implemented that way.

**Comment by steffentchr** [comment]
Yeah, it's validating the chunk on disk to make sure it's fully uploaded. So it's similar, but different ;)
