### ISSUE TITLE
Resumable for Downloads

### ISSUE THREAD

**Issue by vaskaloidis** [23/resumable.js#381]
Hey this is not an issue - just a question.

Is there a similar project for Downloads? **Resumable is an absolutely amazing project / life-saver for some work I have been doing** - and I was wondering if anyone knew a similar project, for chunked file downloads in JS?

Thanks in advance, and thanks for creating such a great JS project!

**Comment by steffentchr** [comment]
First, I don't know of such a project -- and I would add that it might be pretty tricky, since persisting large amounts of data on the client-side from session to session can't/shouldn't be done.

Consider the case of a dropped internet connection that Resumable.js is set up to handle: Someone uploads the first 2 GB of a 3 GB files. In this case, chunks for the the first 2 GB will be stored on the web server -- and when the client comes into work the next morning and uploads again, then the upload will catch up and only upload the last gigabyte of data. 

That's different in the download scenario: Here you would want the browser to store 2 GB in a temp folder somewhere, waiting for the download to maybe be resumed later on. That's a pretty wastful pattern, even if it were possible to do.

Some notes on implementation if anyone is thinking about building:
- It's perfectly possible to [stitch together a file in a browser using multiple `XMLHttpRequest`s](https://developers.google.com/web/updates/2011/08/Saving-generated-files-on-the-client-side).
- Probably a library like this should not have server-side requirement -- but ought to simply use HTTP 1.1's [HTTP Range Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). This would make support pretty much built-in to anything and make deployment easier.
