### ISSUE TITLE
Request.Files.Count returning 0

### ISSUE THREAD

**Issue by BenVS** [23/resumable.js#400]
I'm finding that Request.Files.Count in the server side code is always 0.

This is the javascript code I'm using to send the file.

```
<script src='js/resumable.js?v=03/08/2017 14:45:30' type="text/javascript"> 
</script><form> 
<input type='file' id='browseButton' /> <br><br><br> 
<button id='goButton'>START UPLOAD</button> <br><br><br> 
<script> 
var r = new Resumable({ 
target:'testupload.aspx',  
query:{upload_token:'my_token'} 
}); 
r.assignBrowse(document.getElementById('browseButton'));
r.assignDrop(document.getElementById('dropTarget')); 
document.getElementById('goButton').onclick = function () { 
r.upload();  
};  
</script>

```
But request.files.count always returns 0.

There are no javascript errors.  The target page is reached with the query string params populated:

/testupload.aspx?upload_token=my_token&resumableChunkNumber=1&resumableChunkSize=1048576&resumableCurrentChunkSize=107626&resumableTotalSize=107626&resumableType=image%2Fjpeg&resumableIdentifier=107626-001jpg&resumableFilename=001.jpg&resumableRelativePath=001.jpg&resumableTotalChunks=1

But no file in the Request object. Any help or suggestions would be greatly appreciated.

**Comment by cpnielsen** [comment]
Hi @BenVS 

We generally do not support server-side issues, since we cannot help debug and it is outside the scope of our codebase. Are you using any of the code from our examples?

As far as I can tell with a bit of googling, ASP.NET will not recognize individual chunks as files when posted through an AJAX request (which is what Resumable.js makes use of). I assume the data will be available in `Request.Form` along with the rest of the sent parameters (under "file" if the defaults are used).
